import { TilingSpritePipe } from '../../../../tiling-sprite/TilingSpritePipe';
import { BatcherPipe } from '../../../batcher/shared/BatcherPipe';
import { FilterPipe } from '../../../filters/shared/FilterPipe';
import { FilterSystem } from '../../../filters/shared/FilterSystem';
import { GraphicsContextSystem } from '../../../graphics/shared/GraphicsContextSystem';
import { GraphicsPipe } from '../../../graphics/shared/GraphicsPipe';
import { AlphaMaskPipe } from '../../../mask/shared/AlphaMaskPipe';
import { ColorMaskPipe } from '../../../mask/shared/ColorMaskPipe';
import { StencilMaskPipe } from '../../../mask/shared/StencilMaskPipe';
import { MeshPipe } from '../../../mesh/shared/MeshPipe';
import { LayerPipe } from '../../../scene/LayerPipe';
import { LayerSystem } from '../../../scene/LayerSystem';
import { SpritePipe } from '../../../sprite/shared/SpritePipe';
import { BitmapTextPipe } from '../../../text/bitmap/BitmapTextPipe';
import { CanvasTextPipe } from '../../../text/canvas/CanvasTextPipe';
import { CanvasTextSystem } from '../../../text/canvas/CanvasTextSystem';
import { BackgroundSystem } from '../background/BackgroundSystem';
import { BlendModePipe } from '../BlendModePipe';
import { GlobalUniformSystem } from '../renderTarget/GlobalUniformSystem';
import { UniformBufferSystem } from '../shader/UniformBufferSystem';
import { HelloSystem } from '../startup/HelloSystem';
import { ViewSystem } from '../ViewSystem';
export declare const SharedSystems: (typeof BackgroundSystem | typeof FilterSystem | typeof GraphicsContextSystem | typeof GlobalUniformSystem | typeof HelloSystem | typeof ViewSystem | typeof CanvasTextSystem | typeof LayerSystem | typeof UniformBufferSystem)[];
export declare const SharedRenderPipes: (typeof BatcherPipe | typeof BlendModePipe | typeof SpritePipe | typeof LayerPipe | typeof MeshPipe | typeof GraphicsPipe | typeof CanvasTextPipe | typeof BitmapTextPipe | typeof TilingSpritePipe | typeof FilterPipe | typeof AlphaMaskPipe | typeof StencilMaskPipe | typeof ColorMaskPipe)[];
